### ISSUE TITLE
Add CORS support to server?

### ISSUE THREAD

**Issue by wardle** [wardle/hermes#11]

**Comment by wardle** [comment]
Potentially fixed in 1d0d701d5762da4506900d13c4a008de33f1b1c5 ; needs testing

**Comment by wardle** [comment]
Needs configuration so that this can be switched on or off at runtime, or with specify host(s)

**Comment by sidharthramesh** [comment]
Adding the ability to add arbitrary headers would be a better idea. 

Even the CORS headers [differ a lot](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers#cors) based on the situation. I can definitely see people adding headers like WWW-Authenticate, Cache-Control etc based on their deployment strategy.

**Comment by sidharthramesh** [comment]
Hey @wardle is this solved? How do I enable CORS in the server currently?

**Comment by wardle** [comment]
We could add --allowed-origins with either "*" or a comma delimited list of hosts? Would that work from a usability point of view?

**Comment by sidharthramesh** [comment]
--allowed-origins sounds perfect

**Comment by sidharthramesh** [comment]
Although there are usually other headers to keep in mind too: https://hapifhir.io/hapi-fhir/docs/security/cors.html

**Comment by sidharthramesh** [comment]
For jetty these are the options available: https://gist.github.com/amccarty/66488da19fef8510d9bcaa72d94b218b

**Comment by wardle** [comment]
I can just add the allowed origins interceptor in the pedestal server - and you can add as an option in default interceptors. 

Only issue is what you use for wildcard - I naively thought --allowed-origins * to allow all, but of course, that's a bad idea because of shell expansion. Could have allowed-origins to give a comma delimited list, and another option --allow-all-origins for the wildcard. Latter should be used rarely... surely?

**Comment by wardle** [comment]
My changes seem to work locally using curl, appropriately:
```
curl -I -X OPTIONS \
  -H "Origin: http://example.com" \
  -H 'Access-Control-Request-Method: GET' \
  'http://localhost:8090/v1/snomed/concepts/24700007'
```

I shall commit and can you test? Are you running from source and can you use HEAD, or do you need a jar file for testing?

**Comment by wardle** [comment]
Probably fixed in 55e749b951a42ac17907ce234b81dd857063e02c released for testing as https://github.com/wardle/hermes/releases/tag/v0.8.4--alpha

**Comment by sidharthramesh** [comment]
I can test from the source directly, but thanks for the JAR file, makes things much faster.

**Comment by sidharthramesh** [comment]
It's working correctly 👍 👏. Thank you!
