### ISSUE TITLE
Paginate Search Results

### ISSUE THREAD

**Issue by sidharthramesh** [wardle/hermes#15]
Is there a way to paginate the search results? Something like an `offset` parameter with the search endpoint would be perfect.

**Comment by sidharthramesh** [comment]
Although, increasing the maxHit to get more results is also blazing fast, so it's not really that huge an issue.

**Comment by wardle** [comment]
That's my experience. The numbers you realistically want to show the user are returned quickly enough that you don't need pagination. You'd need pagination to return all of SNOMED but who would want to show that to users?

Not difficult to implement- lucene supports but it just hasn't been a need for me. Ever.

**Comment by sidharthramesh** [comment]
Fair enough
