### ISSUE TITLE
Search by Semantic Tag

### ISSUE THREAD

**Issue by sidharthramesh** [wardle/hermes#16]
While showing a drug list for clinicians to pick from, I am trying to filter out the 'Clinical Drug' and 'Real Clinical Drug'. However, these seem to be semantic tags and not a part of the SNOMED CT hierarchy.  Is it possible to include this information in an ECL? Or is there any way of including the semantic tag in a search?

This is only an issue with the clinical drugs and real clinical drugs semantic tags, since they don't seem to be a part of a hierarchy like Disorders, which can clearly be filtered using an ECL. Related [issue](https://github.com/IHTSDO/snowstorm/issues/36).

**Comment by wardle** [comment]
Is there a way to disambiguate based on relationships other that is-a?

**Comment by sidharthramesh** [comment]
I mean there is this monstrosity
```
<<  373873005 |Pharmaceutical / biologic product (product)| : ( 732944001 |Has presentation strength numerator value (attribute)|  = * OR 733724008 |Has concentration strength numerator value (attribute)| = * )
```
But it slows down the search speeds significantly: About 20 seconds per search!! Usual simple searches on my system take <20ms

**Comment by wardle** [comment]
I guess naive answer would be a two pass approach in which you search FSNs for the tag and then use that denominator set to search. Alternatively perform a search and then do a quick fetch for the FSN and then filter.

**Comment by sidharthramesh** [comment]
Yeah, both could work, but I could also just make a reference set with all the clinical drugs and real clinical drugs and index them in advance. And then do an ECL by `^reference set `.

**Comment by sidharthramesh** [comment]
What really constitutes a "semantic tag"? Just the name in the brackets of an FSN?

**Comment by sidharthramesh** [comment]
How do you filter out clinical drugs in your EHR system? Or maybe you don't use SNOMED for drugs?

**Comment by wardle** [comment]
UK dm+d defines drugs using SNOMED relationships not arbitrary free text in parentheses in a text field.

**Comment by sidharthramesh** [comment]
So what relationships do they establish for you to search only clinical drugs or real clinical drugs? What constraints do you use?

Cause if the Indian release centre is doing it wrong, I could point them to the UK dm+d and maybe they might change how they do it too.

**Comment by wardle** [comment]
Definitely use drugs - see first video on https://wardle.org/patientcare/2018/02/19/so-I-built-an-EPR.html

**Comment by wardle** [comment]
Does the ECL standard provide for semantic tags or search within a FSN? I have a feeling I don't index FSNs by default as I never had the need.

**Comment by wardle** [comment]
In clojure, I'd write a small utility to lazily process the concepts within a specific reference set and create two reference sets from that to disambiguate your drug classes. I'd then use those to drive the UI. 

But if ECL standard has support for this, I'd be happy to look to implement.

**Comment by wardle** [comment]
The UK drug extension specs are available online. They support a six class model - VTM, VMP, VMPP, AMP, AMPP and TF. The semantics aren't quite right either- based on the is-a hierarchies - but each type is in its own refset so you can disambiguate.

**Comment by wardle** [comment]
Although they don't have concrete values - hence why I have built https://github.com/Wardle/dmd - to add a bit more to the base SNOMED drug extension for the UK.

**Comment by wardle** [comment]
Have a look at the ECL filter options, specifically the description type. That looks as if it will give you concepts matching an FSN named something. You could use that in a conjunction to get what you need - maybe! Off the top of my head, I can't remember how much I implemented of this.

**Comment by wardle** [comment]
It looks as if you should be able to use an FSN= filter but the best way is to get people to distribute releases with semantic information as part of the data and not as free text.

**Comment by sidharthramesh** [comment]
> It looks as if you should be able to use an FSN= filter but the best way is to get people to distribute releases with semantic information as part of the data and not as free text.

This seems to be the best approach. I'm writing a script that will quickly look at all of the concepts and add a parent relationship based on the semantic tag and output an extension. I will then index this extension as well. How do you do the indexing? Do I need to output Full, Snapshot and Delta folders? What's the least I can get away with?

**Comment by sidharthramesh** [comment]
> Does the ECL standard provide for semantic tags or search within a FSN? I have a feeling I don't index FSNs by default as I never had the need.

Not yet. But they are apparently planning to add that to the specification soon.

**Comment by wardle** [comment]
You simply need to output a snapshot file - and just adopt the right filename standard - so have a look at that in the specification. The indexing simply [walks the filesystem](https://github.com/wardle/hermes/blob/8b5e0fcf8dad30cd0ecc9e2c909db07882ad3d31/src/com/eldrix/hermes/import.clj#L30) and looks for [filenames that match](https://github.com/wardle/hermes/blob/8b5e0fcf8dad30cd0ecc9e2c909db07882ad3d31/src/com/eldrix/hermes/snomed.clj#L399) - you should be able to recognise the regex even if you can't read clojure - and follow the specs linked in the comment in the source code. Then run your import against a directory containing your file and it will import.

**Comment by wardle** [comment]
My only other suggestion would be to add a "tag" option in your UI definition, and run the logic as an extra step in your UI code. If they add to ECL, I can see how it would be easy to extract the semantic tag from the FSN and stuff into each indexed document in Lucene and then query on that - so it would be trivial - except really they should push distributors to include semantic data in the data - not the free text of a description!
