### ISSUE TITLE
Needs a logo?

### ISSUE THREAD

**Issue by sidharthramesh** [wardle/hermes#17]
Hermes is the only project that is a viable open-source SNOMED server right now. And it needs to get more popular. Having a logo would help.

**Comment by sidharthramesh** [comment]
![image](https://user-images.githubusercontent.com/18082719/117399830-05bc3700-af1f-11eb-9def-3bb9039931a9.png)

**Comment by sidharthramesh** [comment]
I can help if you have an idea of how it should look like

**Comment by wardle** [comment]
A great idea - thanks! I will try to think of an idea!

**Comment by wardle** [comment]
Ok I'm definitely not a graphic artist - as you can see. But what about this?
![hermes-logo](https://user-images.githubusercontent.com/286951/117480153-230df700-af59-11eb-968d-27cc9d716e80.jpg)

**Comment by wardle** [comment]
Something like this? 
![hermes-logo](https://user-images.githubusercontent.com/286951/117480296-53ee2c00-af59-11eb-98dc-7c5257ffc7d4.png)

**Comment by Rutendo-M** [comment]
I like the tortoise.

**Comment by wardle** [comment]
What about this?
![hermes-logo](https://user-images.githubusercontent.com/286951/117480839-03c39980-af5a-11eb-8dc1-9b0ca512330b.png)

**Comment by sidharthramesh** [comment]
It looks great! Just playing the devil's advocate here, but, won't the turtle signal "slow"?

**Comment by wardle** [comment]
Our tortoise is fast! 
![IMG_2167](https://user-images.githubusercontent.com/286951/117483377-8d289b00-af5d-11eb-9d74-a71db2ed7480.jpeg)

**Comment by sidharthramesh** [comment]
Okay then! A tortoise it is!!

**Comment by wardle** [comment]
Yes! Along with the dog, the chickens, guinea pigs, gerbils, snake and leopard gecko! 

Adding wings to the tortoise is beyond my artistic abilities.

**Comment by sidharthramesh** [comment]
![image](https://user-images.githubusercontent.com/18082719/117529227-0a065400-aff4-11eb-8613-662b794d292a.png)

**Comment by sidharthramesh** [comment]
It's a Birtle
