### ISSUE TITLE
Getting Java Class error

### ISSUE THREAD

**Issue by ce-cox** [wardle/hermes#34]
clj -M:run --db snomed.db import ..\
Execution error (UnsupportedClassVersionError) at java.lang.ClassLoader/defineClass1 (REPL:-2).
org/apache/lucene/index/Term has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

Ie  wants JRE version 11 and only v 8 installed.

**Comment by wardle** [comment]
Hi. Lucene 9 uses Java 11. That's the only reason Hermes now needs Java 11. 

You could switch back to lucene 8 in a local branch, but I'd recommend Java 11. It was released 4 years ago. 

I guess I could  offer a runtime configurable option to use Lucene 8 in the deps.edn file but that would then require running tests against two versions of Lucene and ensuring we don't use any of the newer features, which might not be an issue. 

How common is it to still run Java 8?

Mark

**Comment by wardle** [comment]
Try checking out HEAD and then running
```
clj -M:lucene8:run --db snomed.db import xxxxx
```

It will use lucene 8 instead of 9; my tests run successfully against 8.

**Comment by ce-cox** [comment]
Thanks it is running now.

**Comment by wardle** [comment]
Glad to hear it. I'd recommend updating to the latest HEAD (just pushed a moment ago) as I've tweaked the indexing functionality in preparation for ECL2.0 support, otherwise you might get an exception during index creation.

**Comment by wardle** [comment]
Hi. Are you still using hermes with Java 8 and Lucene 8? Lucene 9 has some optimisations and newly deprecated methods that means I am planning on targeting Lucene 9 only. I can target Lucene 8 using macros to switch to older implementations at runtime but this will add a little complexity to the code.

**Comment by wardle** [comment]
From[https://lucene.apache.org/core/corenews.html#apache-lucenetm-950-available]( https://lucene.apache.org/core/corenews.html#apache-lucenetm-950-available):

> Added new stored fields and term vectors interfaces: IndexReader#storedFields and IndexReader#termVectors. These do not rely upon ThreadLocal storage for each index segment, which can greatly reduce RAM requirements when there are many threads and/or segments.

**Comment by wardle** [comment]
See #43
