### ISSUE TITLE
Status info missing

### ISSUE THREAD

**Issue by ce-cox** [wardle/hermes#35]
Hi Mark
Have installed and got it all working fine, many thanks - we will be using this for sure.
One small issue is that I would like to get the status info you describe in the readme but instead I get a list of all the packages, ( as per core.clj ) 
ie I would like to see this count info

{:installed-releases
 ("SNOMED Clinical Terms version: 20200731 [R] (July 2020 Release)"
  "31.3.0_20210120000001 UK clinical extension"),
 :concepts 574414,
 :descriptions 1720404,
 :relationships 3263996,
 :refsets 9424174,
 :indices
 {:descriptions-concept 1720404,
  :concept-parent-relationships 1210561,
  :concept-child-relationships 1210561,
  :installed-refsets 293,
  :component-refsets 6094742,
  :map-target-component 1125516}}

**Comment by wardle** [comment]
Hi. Just use the verbose flag and it will return both installed reference sets and the counts of components.

e.g.

```
cli -M:run --db SNOMED.db status --verbose
```

**Comment by wardle** [comment]
Documentation updated in 690d336ac9d8c4cdd94471125484c4e90b33768c
