### ISSUE TITLE
Excluding Codes

### ISSUE THREAD

**Issue by ce-cox** [wardle/hermes#36]
Hi Mark
I have been told that I need to exclude 3 codes and their children, eg 410663007  <- 246061005 from entering the patient record.
Ideally this would be done when loading from TRUD, but alternatively is there a way to delete a conceptID and all children?
If not could you exclude codes in a config file for the server or least preferable when searching ?

**Comment by wardle** [comment]
That's easy. Just constrain your search with an ECL expression. For this case, you'd add a NOT clause and the concept. You can use << to specify a concept AND its children.

**Comment by ce-cox** [comment]
Hi Mark
My best effort so far is 
constraint=900000000000441003  MINUS (<< 408739003 AND  << 900000000000441003 AND << 410663007)
but it returns a match?

**Comment by ce-cox** [comment]
It would be good to exclude by module as they share the same one but sadly this fails as well
410663007 {{C moduleId != 900000000000012004}}

**Comment by wardle** [comment]
I haven't implemented concept filters, but it would be trivial. I'm still not quite sure what you're trying to achieve however, as it sounds like you're making it more complicated than you need it to be. What are you searching for?

**Comment by ce-cox** [comment]
I have been told that the following codes must not be returned ( or their children ) when a search is run
410663007 | Concept history attribute (attribute) |
408739003 | Unapproved attribute (attribute) |
900000000000441003 | SNOMED CT Model Component (metadata) |

**Comment by wardle** [comment]
A search for what?

**Comment by ce-cox** [comment]
any code or description

**Comment by wardle** [comment]
SNOMED CT is a complex hierarchical terminology. If you let users search across the whole index in a user interface, you'll end up with a mess. You constrain your searches so that the search makes sense in context. e.g. an anatomical structure, a pharmaceutical product, a diagnosis, an ethnicity, a country of birth, an occupation.
