### ISSUE TITLE
How to search?

### ISSUE THREAD

**Issue by sidharthramesh** [wardle/hermes#6]
Hi there Wardle! Thank you for the great work. 
I was able to index my files and get a server up and running. However, I still haven't figured out the API to search for terms.
`http://127.0.0.1:8080/v1/snomed/search? ` returns a lot of concepts, although in a sort of LISP representation:
```
(
#com.eldrix.hermes.impl.search.Result{:id 2616344010, :conceptId 420744004, :term "L", :preferredTerm "Roman numeral L"} 
#com.eldrix.hermes.impl.search.Result{:id 2616333019, :conceptId 420766006, :term "U", :preferredTerm "U"} 
#com.eldrix.hermes.impl.search.Result{:id 2616340018, :conceptId 420925002, :term "z", :preferredTerm "z"} 
...
)
```
How do I search for terms? and Is there a JSON API?

**Comment by wardle** [comment]
Hi. 

For starters, try parameters :

s : search string 
constraint : an ECL constraint


Are you requesting application/json in request header? I should probably set as default but I use as a library at the moment so I've neglected it so far.

**Comment by wardle** [comment]
I've added a tiny fragment of documentation to get you started in the main README. See 656f2d03fc788dfa51d4fab056deaa2382701268
