### ISSUE TITLE
Search API removeDuplicates does not work

### ISSUE THREAD

**Issue by hlab-pawat** [wardle/hermes#62]
# Description

When invoking the /v1/snomed/search API endpoint with removeDuplicates set as a query parameter, the expected behavior is to filter out duplicate concepts in the result set. However, the API still returns duplicated concepts.

## Steps to Reproduce

1. Execute a GET request to the endpoint: <baseURL>/v1/snomed/search?s=hypertension&constraint=%3C404684003&removeDuplicates=1&fallbackFuzzy=1&maxHits=100

2. Observe the response payload.

**Expected Behavior**
The API should return unique concept IDs based on the removeDuplicates parameter. For example, concept ID 38341003 should appear only once in the results.

**Actual Behavior**
The API response includes multiple instances of the same concept ID. For instance, concept ID 38341003 appears several times with different id values but referring to the same "Hypertensive disorder" concept.

**Example response**
```
[
	{
		"id": 64176011,
		"conceptId": 38341003,
		"term": "Hypertension",
		"preferredTerm": "Hypertensive disorder"
	},
	{
		"id": 64170017,
		"conceptId": 38341003,
		"term": "Hypertension, NOS",
		"preferredTerm": "Hypertensive disorder"
	},
	{
		"id": 490281011,
		"conceptId": 38341003,
		"term": "HT - Hypertension",
		"preferredTerm": "Hypertensive disorder"
	},
	{
		"id": 490283014,
		"conceptId": 38341003,
		"term": "BP+ - Hypertension",
		"preferredTerm": "Hypertensive disorder"
	},
	{
		"id": 2164904016,
		"conceptId": 38341003,
		"term": "HTN - Hypertension",
		"preferredTerm": "Hypertensive disorder"
	},
	{
		"id": 47076011,
		"conceptId": 28119000,
		"term": "Renal hypertension",
		"preferredTerm": "Renal hypertension"
	},
	{
		"id": 3285652012,
		"conceptId": 712832005,
		"term": "Supine hypertension",
		"preferredTerm": "Supine hypertension"
	},
        ....
]
```

This issue leads to confusion regarding the functionality of the removeDuplicates parameter and its intended use.

## Environment
* Application version: 1.4.1351
* Database: SNOMED CT international edition, version 2024-02

I am seeking clarification on whether my understanding of the removeDuplicates parameter's purpose is correct and if this behavior is expected or indicative of a bug.

**Comment by wardle** [comment]
Hi. Thanks for this. 

It is working as intended removing consecutive results with the "same conceptId and text". 

This is intended to help support a better user experience. You would usually want the different synonyms of a single concept, but in recent distributions there have been synonyms with the same textual content (term) resulting in what appears to be duplicates in your user interface.

**Comment by hlab-pawat** [comment]
Thank you for your reply and awesome SNOMED api. I got the intension of removeDuplicates parameter.

**Comment by wardle** [comment]
Glad it is working for you. I have added some more detail in the README on the rationale behind this flag.

It is not the default to maintain backwards compatibility with previous behaviour and because clients may wish to handle the user experience in a different way.
