### ISSUE TITLE
Add support for parallelised result collection via new CollectorManager API

### ISSUE THREAD

**Issue by wardle** [wardle/hermes#63]
This might speed up queries but will need testing. The CollectorManager API permits parallelised collection of results. One uses a CollectorManager which can create new collectors, and then once all results have been collected, it has the responsibility of reducing across all collectors.

**Comment by wardle** [comment]
Further investigation demonstrates that the parallelisation occurs based only on the number of segments in an index file. As such, if the index is compacted, such that there is a single segment [which is what we do], then only a single collector is actually used. This means that the CollectorManager simply adds a tiny bit of overhead. This is the case even if the IndexSearcher is created with an executor service that supports multiple threads. As such, the only reason for adopting the CollectorManager API is to avoid deprecation notices from directly using a Collector in the search method of an IndexSearcher.

**Comment by wardle** [comment]
Testing demonstrates that even when an IndexSearcher is created using a thread pool:
e.g.
```
(IndexSearcher. index-reader (Executors/newFixedThreadPool 8))
```

When the index has only one segment, only one thread is used to collect the results.

**Comment by wardle** [comment]
The implementation of CollectionManager is straightforward:

```
; A Lucene results collector that collects *all* results into the mutable
;; java collection 'coll'.
(deftype IntoArrayCollector [^List coll]
  Collector
  (getLeafCollector [_ ctx]
    (let [base-id (.-docBase ctx)]
      (reify LeafCollector
        (^void setScorer [_ ^Scorable _scorer])                             ;; NOP
        (^void collect [_ ^int doc-id]
          (.add coll (+ base-id doc-id))))))
  (scoreMode [_] ScoreMode/COMPLETE_NO_SCORES))

;; A Lucene CollectorManager that can collect results in parallel and then
;; create a lazy concatenation of the results once search is complete
(deftype IntoSequenceCollectorManager []
  CollectorManager
  (newCollector [_]
    (IntoArrayCollector. (ArrayList.)))
  (reduce [_ collectors]
    (mapcat #(.-coll ^IntoArrayCollector %) collectors)))
```

And the implementation of a streaming API along the same lines is similarly easy:

```
;; A Lucene Collector that puts search results onto a core.async channel
(deftype IntoChannelCollector [ch]
  Collector
  (getLeafCollector [_ ctx]
    (let [base-id (.-docBase ctx)]
      (reify LeafCollector
        (^void setScorer [_ ^Scorable _scorer])                             ;; NOP
        (^void collect [_ ^int doc-id]
          (when-not (a/>!! ch (+ base-id doc-id))           ;; put the document on the channel, but if channel closed...
            (throw (CollectionTerminatedException.)))))))   ;; ... then prematurely terminate collection of the current leaf
  (scoreMode [_] ScoreMode/COMPLETE_NO_SCORES))

;; A Lucene CollectorManager that can collect results in parallel putting
;; results onto a channel, optionally closing when done.
(deftype IntoChannelCollectorManager [ch close?]
  CollectorManager
  (newCollector [_]
    (IntoChannelCollector. ch))
  (reduce [_ _]
    (when close? (a/close! ch))))

```

**Comment by wardle** [comment]
One would simply replace the existings function definitions to use the new CollectorManager implementations:
```
(defn search-all
  [^IndexSearcher searcher ^Query q]
  (.search searcher q (IntoSequenceCollectorManager.)))
```
and

```
(defn stream-all
  ([^IndexSearcher searcher ^Query q ch]
   (stream-all searcher q ch true))
  ([^IndexSearcher searcher ^Query q ch close?]
   (.search searcher q (IntoChannelCollectorManager. ch close?))))
```

**Comment by wardle** [comment]
Testing shows that they give the same results

**Comment by wardle** [comment]
Committed in 3ecc7a3a7f5d52c54e70059974de05a9787b177c but apart from avoiding deprecated methods, no significant benefit.

**Comment by wardle** [comment]
Also see https://github.com/apache/lucene/issues/11041#issuecomment-2018982902

**Comment by wardle** [comment]
On further benchmarking, the direct use of a Collector vs using a CollectorManager has minimal overhead, and I can sympathise with the API changes in Lucene in making it less likely to do the wrong thing by simplifying the API and enabling parallelisation when appropriate. Indeed, one might argue it might be of benefit if there is an index with multiple updates in place.

**Comment by mikemccand** [comment]
I read your transient comment on the Lucene issue about having a single segment and not needing the search-time concurrency, which makes sense.

But note that Lucene devs have long wanted to decouple search-time concurrency from segment geometry.  Right now, a single segment (used to be called "optimized") means no intra-query concurrency, which is sort of crazy.  In fact, working on this improvement is [one of the three biggies that we are hoping to do before Lucene's next major (10.0) release](https://lists.apache.org/thread/4bhnkkvvodxxgrpj4yqm5yrgj0ppc59r).

Finally, when we make a major change to Lucene APIs that impact users like you, we try to include details in the `lucene/MIGRATE.md` explaining how to switch to the new API, but I don't see any mention of this in Lucene's `main` (to be 10.0) `MIGRATE.md`.  I'll open a Lucene issue to hopefully get this fixed before we release...

**Comment by mikemccand** [comment]
No need to delete comments like yours in the future!  It's really awesome for we Lucene devs to hear from our users, and to see our API changes through your "fresh eyes".  We are too blind to these impacts.

> It would be nice to be able to dial-in some concurrency for a single segment index if appropriate so looking forward to seeing the next release!

+1 -- I would love to see us finally implement this improvement.  It is a long-standing and embarrassing limitation on Lucene's intra-query concurrency, especially since Lucene's Query scoring APIs already have the underlying capabilities needed to efficiently create multiple thread "work units" for a single large segment.
